CHITRA = "d:/ymir work/ui/login_interface/"
BUTTON_CHITRA = "d:/ymir work/ui/login_interface/button/" 
BUTTON_INTERFACE = "d:/ymir work/ui/login_interface/buttons/" 
TEXT_INTERFACE = "d:/ymir work/ui/login_interface/text/" 
INPUT_INTERFACE = "d:/ymir work/ui/login_interface/input/"

LOGIN_BOARD_MARGIN = 100

if SCREEN_HEIGHT < 800:
	LOGO_MARGIN = 150
	LOGIN_BOARD_MARGIN = 200
	
if SCREEN_HEIGHT < 610:
	LOGO_MARGIN = 350
	LOGIN_BOARD_MARGIN = 250
	
LOGIN_BOARD_POS_Y = (SCREEN_HEIGHT/2) - LOGIN_BOARD_MARGIN

window = {
	"sytle" : ("movable",),
	"x" : 0, "y" : 0,
	"width" : SCREEN_WIDTH,
	"height" : SCREEN_HEIGHT,
	"children" : 
	(
		{
			"name" : "background", 
			"type" : "expanded_image",
			"x" : 0, "y" : 0,
			"x_scale" : float(SCREEN_WIDTH) / 1920.0,
			"y_scale" : float(SCREEN_HEIGHT) / 1080.0,
			"image" : CHITRA + "background.tga",
		},
		{
			"name" : "board_logo",
			"type" : "image",
			'x' : (SCREEN_WIDTH - 630) / 2,
			"y" : 0, #centered middle
			"x_scale" : float(SCREEN_WIDTH) / 1400.0,
			"y_scale" : float(SCREEN_HEIGHT) / 590.0,
			"image" : CHITRA + "logo_background.tga",
			# "children" :
			# (
				# {
				
				# },
			# ),
		},
		{
			"name" : "board_main",
			"type" : "image",
			'x' : (SCREEN_WIDTH - 1500) / 2,
			"y" : LOGIN_BOARD_POS_Y - 100, #centered middle
			"x_scale" : float(SCREEN_WIDTH) / 1400.0,
			"y_scale" : float(SCREEN_HEIGHT) / 590.0,
			"image" : CHITRA + "bg_bg.tga",
			"children" :
			(
				{
					"name" : "board_login",
					"type" : "image",
					'x' : 200,
					"y" : 0,
					"image" : CHITRA + "board.tga",
					"children" :
					(
						{
							"name" : "id_slotbar",
							"type" : "image",
							"x" : 0, "y" : 0,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"image" : INPUT_INTERFACE + "input.tga",
							"children" : 
							(
								{
									"name" : "id",
									"type" : "editline",
									"x" : 20, "y" : 13,
									"width" : 200, "height" : 16,
									"color" : 0xff494949,
									"input_limit": 16,
								},
							),
						},
						{
							"name" : "pwd_slotbar",
							"type" : "image",
							"x" : 0, "y" : 45,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"image" : INPUT_INTERFACE + "input.tga",
							"children" : 
							(
								{
									"name" : "pwd",
									"type" : "editline",
									"x" : 20, "y" : 13,
									"width" : 200, "height" : 16,
									"color" : 0xff494949,
									"input_limit": 16,
									"secret_flag": 1,
								},
							),
						},
						{
							"name" : "login_button",
							"type" : "button",
							"x" : 0, "y" : 150,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"default_image" : BUTTON_INTERFACE + "login_1.tga", 
							"over_image" : BUTTON_INTERFACE + "login_2.tga",
							"down_image" : BUTTON_INTERFACE + "login_3.tga",
							# "children" : 
							# (
								# {
									# "name" : "login_text",
									# "type" : "image",
									# "x" : 0, "y" : 0,
									# "horizontal_align" : "center",
									# "vertical_align" : "center",
									# "image" : TEXT_INTERFACE + "login_text.tga",
								# },
							# ),
						},
						# {
							# "name" : "forgot_password",
							# "type" : "image",
							# "x" : 0, "y" : 230,
							# "horizontal_align" : "center",
							# "vertical_align" : "center",
							# "image" : TEXT_INTERFACE + "forgotpw_text.tga",
						# },
						{
							"name" : "selected_channel1",
							"type" : "image",
							"x" : 0, "y" : 90,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"image" : TEXT_INTERFACE + "selected_ch1.tga",
						},
						{
							"name" : "selected_channel2",
							"type" : "image",
							"x" : 0, "y" : 90,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"image" : TEXT_INTERFACE + "selected_ch2.tga",
						},
						{
							"name" : "selected_channel3",
							"type" : "image",
							"x" : 0, "y" : 90,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"image" : TEXT_INTERFACE + "selected_ch3.tga",
						},
						{
							"name" : "selected_channel4",
							"type" : "image",
							"x" : 0, "y" : 90,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"image" : TEXT_INTERFACE + "selected_ch4.tga",
						},
						{
							"name" : "selected_channel5",
							"type" : "image",
							"x" : 0, "y" : 90,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"image" : TEXT_INTERFACE + "selected_ch5.tga",
						},
						{
							"name" : "selected_channel6",
							"type" : "image",
							"x" : 0, "y" : 90,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"image" : TEXT_INTERFACE + "selected_ch6.tga",
						},
					),
				},
				# Channel Area #
				{
					"name" : "board_channel",
					"type" : "image",
					'x' : 480,
					"y" : 30,
					"image" : CHITRA + "board.tga",
					"children" :
					(
						{
							"name" : "channel1_label",
							"type" : "image",
							"x" : 0, "y" : 0,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"image" : TEXT_INTERFACE + "channel_1.tga",
						},
						{
							"name" : "ch1",
							"type" : "radio_button",
							"x" : 90, "y" : 0,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"default_image" : BUTTON_INTERFACE + "hook_0.tga",
							"over_image" : BUTTON_INTERFACE + "hook_1.tga",
							"down_image" : BUTTON_INTERFACE + "hook_2.tga",
							"children" :
							(
								{
									"name" : "channel1_status",
									"type" : "image",
									"x" : 45, "y" : 0,
									"horizontal_align" : "center",
									"vertical_align" : "center",
									"image" : TEXT_INTERFACE + "online.tga",
								},
							),
						},
						{
							"name" : "channel2_label",
							"type" : "image",
							"x" : 0, "y" : 30,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"image" : TEXT_INTERFACE + "channel_2.tga",
						},
						{
							"name" : "ch2",
							"type" : "radio_button",
							"x" : 90, "y" : 30,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"default_image" : BUTTON_INTERFACE + "hook_0.tga",
							"over_image" : BUTTON_INTERFACE + "hook_1.tga",
							"down_image" : BUTTON_INTERFACE + "hook_2.tga",
							"children" :
							(
								{
									"name" : "channel2_status",
									"type" : "image",
									"x" : 45, "y" : 0,
									"horizontal_align" : "center",
									"vertical_align" : "center",
									"image" : TEXT_INTERFACE + "online.tga",
								},
							),
						},
						{
							"name" : "channel3_label",
							"type" : "image",
							"x" : 0, "y" : 60,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"image" : TEXT_INTERFACE + "channel_3.tga",
						},
						{
							"name" : "ch3",
							"type" : "radio_button",
							"x" : 90, "y" : 60,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"default_image" : BUTTON_INTERFACE + "hook_0.tga",
							"over_image" : BUTTON_INTERFACE + "hook_1.tga",
							"down_image" : BUTTON_INTERFACE + "hook_2.tga",
							"children" :
							(
								{
									"name" : "channel3_status",
									"type" : "image",
									"x" : 45, "y" : 0,
									"horizontal_align" : "center",
									"vertical_align" : "center",
									"image" : TEXT_INTERFACE + "online.tga",
								},
							),
						},
						{
							"name" : "channel4_label",
							"type" : "image",
							"x" : 0, "y" : 90,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"image" : TEXT_INTERFACE + "channel_4.tga",
						},
						{
							"name" : "ch4",
							"type" : "radio_button",
							"x" : 90, "y" : 90,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"default_image" : BUTTON_INTERFACE + "hook_0.tga",
							"over_image" : BUTTON_INTERFACE + "hook_1.tga",
							"down_image" : BUTTON_INTERFACE + "hook_2.tga",
							"children" :
							(
								{
									"name" : "channel4_status",
									"type" : "image",
									"x" : 45, "y" : 0,
									"horizontal_align" : "center",
									"vertical_align" : "center",
									"image" : TEXT_INTERFACE + "online.tga",
								},
							),
						},
						{
							"name" : "channel5_label",
							"type" : "image",
							"x" : 0, "y" : 120,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"image" : TEXT_INTERFACE + "channel_5.tga",
						},
						{
							"name" : "ch5",
							"type" : "button",
							"x" : 90, "y" : 120,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"default_image" : BUTTON_INTERFACE + "hook_0.tga",
							"over_image" : BUTTON_INTERFACE + "hook_1.tga",
							"down_image" : BUTTON_INTERFACE + "hook_2.tga",
							"children" :
							(
								{
									"name" : "channel5_status",
									"type" : "image",
									"x" : 45, "y" : 0,
									"horizontal_align" : "center",
									"vertical_align" : "center",
									"image" : TEXT_INTERFACE + "channel_state_offline.tga",
								},
							),
						},
						{
							"name" : "channel6_label",
							"type" : "image",
							"x" : 0, "y" : 150,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"image" : TEXT_INTERFACE + "channel_6.tga",
						},
						{
							"name" : "ch6",
							"type" : "button",
							"x" : 90, "y" : 150,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"default_image" : BUTTON_INTERFACE + "hook_0.tga",
							"over_image" : BUTTON_INTERFACE + "hook_1.tga",
							"down_image" : BUTTON_INTERFACE + "hook_2.tga",
							"children" :
							(
								{
									"name" : "channel6_status",
									"type" : "image",
									"x" : 45, "y" : 0,
									"horizontal_align" : "center",
									"vertical_align" : "center",
									"image" : TEXT_INTERFACE + "channel_state_offline.tga",
								},
							),
						},
					),
				},
				# SAVED ACCS Area #
				{
					"name" : "board_saveacc",
					"type" : "image",
					'x' : 775,
					"y" : 20,
					"image" : CHITRA + "board.tga",
					"children" :
					(
						# # # # # # # # # 1 # #  # # # # # #
						{
							"name" : "saved_accs_acc1",
							"type" : "text",
							"x" : 0, "y" : 0,
							"color" : 0xff494949,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"text":"Acc3",
						},
						{
							"name" : "saved_accs_acc1_use",
							"type" : "button",
							"x" : 120, "y" : 5,
							"default_image" : BUTTON_INTERFACE + "hook_1.tga",
							"over_image" : BUTTON_INTERFACE + "hook_2.tga",
							"down_image" : BUTTON_INTERFACE + "hook_3.tga",
							"horizontal_align" : "center",
							"vertical_align" : "center",
						},
						{
							"name" : "save_acc1",
							"type" : "button",
							"x" : 130, "y" : 5,
							"default_image" : BUTTON_INTERFACE + "save_1.tga",
							"over_image" : BUTTON_INTERFACE + "save_2.tga",
							"down_image" : BUTTON_INTERFACE + "save_3.tga",
							"horizontal_align" : "center",
							"vertical_align" : "center",
						},
						{
							"name" : "saved_accs_acc1_del",
							"type" : "button",
							"x" : 140, "y" : 5,
							"default_image" : BUTTON_INTERFACE + "x_1.tga",
							"over_image" : BUTTON_INTERFACE + "x_2.tga",
							"down_image" : BUTTON_INTERFACE + "x_3.tga",
							"horizontal_align" : "center",
							"vertical_align" : "center",
						},
						# # # # # # # # # 2 # #  # # # # # #
						{
							"name" : "saved_accs_acc2",
							"type" : "text",
							"x" : 0, "y" : 30,
							"color" : 0xff494949,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"text":"Acc2",
						},
						{
							"name" : "saved_accs_acc2_use",
							"type" : "button",
							"x" : 120, "y" : 35,
							"default_image" : BUTTON_INTERFACE + "hook_1.tga",
							"over_image" : BUTTON_INTERFACE + "hook_2.tga",
							"down_image" : BUTTON_INTERFACE + "hook_3.tga",
							"horizontal_align" : "center",
							"vertical_align" : "center",
						},
						{
							"name" : "save_acc2",
							"type" : "button",
							"x" : 130, "y" : 35,
							"default_image" : BUTTON_INTERFACE + "save_1.tga",
							"over_image" : BUTTON_INTERFACE + "save_2.tga",
							"down_image" : BUTTON_INTERFACE + "save_3.tga",
							"horizontal_align" : "center",
							"vertical_align" : "center",
						},
						{
							"name" : "saved_accs_acc2_del",
							"type" : "button",
							"x" : 140, "y" : 35,
							"default_image" : BUTTON_INTERFACE + "x_1.tga",
							"over_image" : BUTTON_INTERFACE + "x_2.tga",
							"down_image" : BUTTON_INTERFACE + "x_3.tga",
							"horizontal_align" : "center",
							"vertical_align" : "center",
						},
						# # # # # # # # # 3 # #  # # # # # #
						{
							"name" : "saved_accs_acc3",
							"type" : "text",
							"x" : 0, "y" : 60,
							"color" : 0xff494949,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"text":"Acc4",
						},
						{
							"name" : "saved_accs_acc3_use",
							"type" : "button",
							"x" : 120, "y" : 65,
							"default_image" : BUTTON_INTERFACE + "hook_1.tga",
							"over_image" : BUTTON_INTERFACE + "hook_2.tga",
							"down_image" : BUTTON_INTERFACE + "hook_3.tga",
							"horizontal_align" : "center",
							"vertical_align" : "center",
						},
						{
							"name" : "save_acc3",
							"type" : "button",
							"x" : 130, "y" : 65,
							"default_image" : BUTTON_INTERFACE + "save_1.tga",
							"over_image" : BUTTON_INTERFACE + "save_2.tga",
							"down_image" : BUTTON_INTERFACE + "save_3.tga",
							"horizontal_align" : "center",
							"vertical_align" : "center",
						},
						{
							"name" : "saved_accs_acc3_del",
							"type" : "button",
							"x" : 140, "y" : 65,
							"default_image" : BUTTON_INTERFACE + "x_1.tga",
							"over_image" : BUTTON_INTERFACE + "x_2.tga",
							"down_image" : BUTTON_INTERFACE + "x_3.tga",
							"horizontal_align" : "center",
							"vertical_align" : "center",
						},
						# # # # # # # # # 4 # #  # # # # # #
						{
							"name" : "saved_accs_acc4",
							"type" : "text",
							"x" : 0, "y" : 90,
							"color" : 0xff494949,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"text":"Acc4",
						},
						{
							"name" : "saved_accs_acc4_use",
							"type" : "button",
							"x" : 120, "y" : 95,
							"default_image" : BUTTON_INTERFACE + "hook_1.tga",
							"over_image" : BUTTON_INTERFACE + "hook_2.tga",
							"down_image" : BUTTON_INTERFACE + "hook_3.tga",
							"horizontal_align" : "center",
							"vertical_align" : "center",
						},
						{
							"name" : "save_acc4",
							"type" : "button",
							"x" : 130, "y" : 95,
							"default_image" : BUTTON_INTERFACE + "save_1.tga",
							"over_image" : BUTTON_INTERFACE + "save_2.tga",
							"down_image" : BUTTON_INTERFACE + "save_3.tga",
							"horizontal_align" : "center",
							"vertical_align" : "center",
						},
						{
							"name" : "saved_accs_acc4_del",
							"type" : "button",
							"x" : 140, "y" : 95,
							"default_image" : BUTTON_INTERFACE + "x_1.tga",
							"over_image" : BUTTON_INTERFACE + "x_2.tga",
							"down_image" : BUTTON_INTERFACE + "x_3.tga",
							"horizontal_align" : "center",
							"vertical_align" : "center",
						},
						# # # # # # # # # 5 # #  # # # # # #
						{
							"name" : "saved_accs_acc5",
							"type" : "text",
							"x" : 0, "y" : 120,
							"color" : 0xff494949,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"text":"Acc5",
						},
						{
							"name" : "saved_accs_acc5_use",
							"type" : "button",
							"x" : 120, "y" : 125,
							"default_image" : BUTTON_INTERFACE + "hook_1.tga",
							"over_image" : BUTTON_INTERFACE + "hook_2.tga",
							"down_image" : BUTTON_INTERFACE + "hook_3.tga",
							"horizontal_align" : "center",
							"vertical_align" : "center",
						},
						{
							"name" : "save_acc5",
							"type" : "button",
							"x" : 130, "y" : 125,
							"default_image" : BUTTON_INTERFACE + "save_1.tga",
							"over_image" : BUTTON_INTERFACE + "save_2.tga",
							"down_image" : BUTTON_INTERFACE + "save_3.tga",
							"horizontal_align" : "center",
							"vertical_align" : "center",
						},
						{
							"name" : "saved_accs_acc5_del",
							"type" : "button",
							"x" : 140, "y" : 125,
							"default_image" : BUTTON_INTERFACE + "x_1.tga",
							"over_image" : BUTTON_INTERFACE + "x_2.tga",
							"down_image" : BUTTON_INTERFACE + "x_3.tga",
							"horizontal_align" : "center",
							"vertical_align" : "center",
						},
						# # # # # # # # # 6 # #  # # # # # #
						{
							"name" : "saved_accs_acc6",
							"type" : "text",
							"x" : 0, "y" : 150,
							"color" : 0xff494949,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"text":"Acc6",
						},
						{
							"name" : "saved_accs_acc6_use",
							"type" : "button",
							"x" : 120, "y" : 155,
							"default_image" : BUTTON_INTERFACE + "hook_1.tga",
							"over_image" : BUTTON_INTERFACE + "hook_2.tga",
							"down_image" : BUTTON_INTERFACE + "hook_3.tga",
							"horizontal_align" : "center",
							"vertical_align" : "center",
						},
						{
							"name" : "save_acc6",
							"type" : "button",
							"x" : 130, "y" : 155,
							"default_image" : BUTTON_INTERFACE + "save_1.tga",
							"over_image" : BUTTON_INTERFACE + "save_2.tga",
							"down_image" : BUTTON_INTERFACE + "save_3.tga",
							"horizontal_align" : "center",
							"vertical_align" : "center",
						},
						{
							"name" : "saved_accs_acc6_del",
							"type" : "button",
							"x" : 140, "y" : 155,
							"default_image" : BUTTON_INTERFACE + "x_1.tga",
							"over_image" : BUTTON_INTERFACE + "x_2.tga",
							"down_image" : BUTTON_INTERFACE + "x_3.tga",
							"horizontal_align" : "center",
							"vertical_align" : "center",
						},
					),
				},
			),
		},
	),
}